version: '2.1'

services:

  # ------------------------------------------------------------------------------------
  # Industrial data collection and management - N3uron
  # ------------------------------------------------------------------------------------
  n3uron:
    image: n3uronhub/n3uron:v1.21.4
    hostname: n3uron-balena
    networks:
      default:
        aliases:
          - n3uron-balena
    ports:
      - 8003:8003
      - 443:8443
    volumes:
      - n3_config:/opt/n3uron/config
      - n3_data:/opt/n3uron/data
      - n3_licenses:/opt/n3uron/licenses
      - n3_log:/opt/n3uron/log
    restart: always
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    environment:
      - UDEV=1
      - MONGO_URL=mongodb://mongodb:27017/
    privileged: true
    labels:
      io.balena.features.balena-socket: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
  
  # ------------------------------------------------------------------------------------
  # MQTT broker - HiveMQ 4 
  # ------------------------------------------------------------------------------------
  # hivemq:
  #   image: hivemq/hivemq-ce:snapshot
  #   ports:
  #     - 1883:1883 # MQTT/TCP protocol port
  #     - 8080:8080
  #   environment:
  #     JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:InitialRAMPercentage=30 -XX:MaxRAMPercentage=80 -XX:MinRAMPercentage=30"

  hivemq4:
    build: ./hivemq4
    ports:
      - 1883:1883 # MQTT/TCP protocol port
      - 8080:8080 # Control Center port
      - 8000:8000 # Websockets port
    volumes:
      - hivemq_data:/opt/hivemq/data                     # Make broker data persistent throughout stop/start cycles
      - hivemq_log:/opt/hivemq/log                       # Persist log data
      - hivemq_license:/opt/hivemq/license               # Persist HiveMQ license
    environment:
      JAVA_OPTS: "-XX:+UnlockExperimentalVMOptions -XX:InitialRAMPercentage=30 -XX:MaxRAMPercentage=80 -XX:MinRAMPercentage=30"
      HIVEMQ_BRIDGE_EXTENSION: false
      HIVEMQ_HOST_URL: "HIVEMQ_HOST_URL"
      HIVEMQ_HOST_PORT: "HIVEMQ_HOST_PORT"
      HIVEMQ_HOST_USERNAME: "HIVEMQ_HOST_USERNAME"
      HIVEMQ_HOST_PASSWORD: "HIVEMQ_HOST_PASSWORD"
      HIVEMQ_TLS_ENABLED: false
      HIVEMQ_TOPICS_CONFIGURATION: "<filter>#</filter>"
      HIVEMQ_CONNECTION_ENABLED: false
  
  # ------------------------------------------------------------------------------------
  # Historian database - MongoDB
  # ------------------------------------------------------------------------------------
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: balena
      MONGO_INITDB_ROOT_PASSWORD: balena
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  n3_config:
  n3_data:
  n3_licenses:
  n3_log:
  mongo_data:
  hivemq_data:
  hivemq_log:
  hivemq_license:
